# Worked Examples 06

In this exercise, you will practice aggregating and summarizing data with Pandas `groupby` and `pivot_table` and merging/joining datasets using Pandas `concat` and `merge`.

Unlike Homeworks, the autograders for worked examples are embedded with the questions so that you can run the tests yourself. Read the instructions below carefully.

In [1]:
# Here are the needed imports, make sure to run this cell
import seaborn as sns
import pandas as pd
import numpy as np

### Autograder Instructions

Run the following cell to install the `Otter` autograder package the first time it is run. Afterwards, running it again will print out its version number if `Otter` is correctly installed.

In [2]:
try:
    import otter
    grader = otter.Notebook("worked-example06.ipynb")
    print(otter.__version__)
    if (otter.__version__ != '6.1.6'): #update for latest otter version
        %pip install -U --user otter-grader
except Exception as e:
    %pip install otter-grader

6.1.6

Unlike Homeworks, the autograders for worked examples are embedded with the questions so that you can run the tests yourself. To grade your own work, simply run the cell starting with `grader.check` immediately after each question. The cell calls Otter to run the tests for all subquestions and generate a report of what test(s) you pass/do not pass in the same style as on Gradescope.

## Part 1: Summarizing Data
In this part we will start by working with the `seaborn` `planets` dataset. Seaborn is a library for data visualization in Python (already included in your Anaconda distribution) to which we will be returning soon. For now, we are just using it for easy access to the `planets` dataset containing information about 1,035 extrasolar planets that have been discovered by Astronomers over the last several years. As an aside, extrasolar planet discovery is an excellent example of how data science can help fuel discovery in the sciences by automating the analysis of large quantities of data, in this case from telescopes. If you're interested (not necessary to complete this assignment), you can read more at https://exoplanets.nasa.gov, from which this dataset was originally drawn.

To begin, run the following code to import the dataset into the `planets` DataFrame and preview the first five rows.

In [3]:
# Run but do not modify this code
planets = sns.load_dataset('planets')
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

### Question 1
Use Pandas `groupby` operations to answer the following. You might find the function [Series.idxmax](https://pandas.pydata.org/docs/reference/api/pandas.Series.idxmax.html) useful.

1. If you run the code `planets.groupby("number").count()` you will see different values for the different columns. Why is that? Put your answer in "Answer q1_1" cell.
2. What are the two `method`s that account for the most discoveries? How many discoveries were made with those `method`s? Put your answer in `q1_2`. It should have the type `Series` and the index value is the method and the corresponding data is the number of discoveries. You should be able to create this by indexing into the `GroupBy` object to select the correct rows and columns.
3. In which years were more than 100 discoveries made? Put your answer in `q1_3`. It should be the type `numpy.ndarray`.
4. Which `method` has found the most distant exoplanets on average (i.e., the `distance` column), and what is that average distance? Put the method name (string) in `q1_4_1` and the average distance (float) in `q1_4_2`.
5. Which `method` has found the single most distant exoplanet in the dataset, and what `distance` is that exoplanet? Put the method name (string) in `q1_5_1` and the distance (float) in `q1_5_2`.

_Type your answer here, replacing this text._

<!-- END QUESTION -->

In [5]:
# Put your code to answer the question here
# Feel free to add additional cells
q1_2 = ...
q1_3 = ...
q1_4_1 = ...
q1_4_2 = ...
q1_5_1 = ...
q1_5_2 = ...

In [ ]:
grader.check("q1")

### Question 2
Next we will work with the titanic dataset which contains historical information about the passengers of the cruiseship *Titanic* that sank in the North Atlantic in 1912. Import the dataset and preview the first few rows below.

In [6]:
# Run but do not modify this code
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Use Pandas `pivot_table`s to answer the following.

1. Create a DataFrame with the average fare paid by passengers grouped by each combination of `sex` and `class`. Put the result in `q2_1`, the column should be `class` and index should be `sex`.

2. Create a DataFrame with the number of passengers grouped by each combination of `class` and `embark_town`. Put the result in `q2_2`, the column should be `embark_town` and index should be `class`.

3. Create a DataFrame with the fraction of passengers who survived (i.e., `survived==1`) grouped by each combination of `sex`, `class`, and `embark_town`. Put the result in `q2_3`, the column should be `embark_town` and indices should be `sex` and `class`.
  1. For example, if there are four individuals of a given `sex`, `class`, and `embark_town`, and three of the four survived, the value for that combination would be `0.75`.

4. Create a DataFrame with the average `age` and the total `fare` paid by passengers grouped by each combination of `class` and `sex`. `age` should be first and `fare` second. Put the result in `q2_4`, the column should be sex (for average `age` and the total `fare` respectively) and index should be class.
  1. For example, if there were just 2 passengers with `class==first` and `sex==male` aged `20` and `30` and having paid `fare`s of `50` and `70` each, then the average age of that combination would be `25` and the total `fare` paid would be `120`.

In [7]:
# Put your code to answer the question here
# Feel free to add additional cells, especially 
# for displaying tables
q2_1 = titanic.pivot_table(values='fare', index='sex', columns='class', aggfunc='mean')
q2_2 = titanic.pivot_table(values='survived', index='class', columns='embark_town', aggfunc='count')
q2_3 = titanic.pivot_table(values='survived', index=['sex', 'class'], columns='embark_town', aggfunc='mean')
q2_4_age = titanic.pivot_table(values='age', index='class', columns='sex', aggfunc='mean')
q2_4_fare = titanic.pivot_table(values='fare', index='class', columns='sex', aggfunc='sum')
# Combine into a multi-indexed DataFrame, as required
q2_4 = pd.concat([q2_4_age, q2_4_fare], keys=['age', 'fare'])

/var/folders/zr/5crywxy91hl91sm9xrmd03kc0000gn/T/ipykernel_85203/3245240486.py:4: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  q2_1 = titanic.pivot_table(values='fare', index='sex', columns='class', aggfunc='mean')
/var/folders/zr/5crywxy91hl91sm9xrmd03kc0000gn/T/ipykernel_85203/3245240486.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  q2_2 = titanic.pivot_table(values='survived', index='class', columns='embark_town', aggfunc='count')
/var/folders/zr/5crywxy91hl91sm9xrmd03kc0000gn/T/ipykernel_85203/3245240486.py:6: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  q2_3 = titanic.pivot_table(values='survived', index=['sex', 'class'], columns='embark_town', aggfunc='mean')
/var/folders/zr/5crywxy91hl91sm9xrmd03kc0000gn/T/ipykernel_85203/3245240486.py:7: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  q2_4_age = titanic.pivot_table(values='age', index='class', columns='sex', aggfunc='mean')
/var/folders/zr/5crywxy91hl91sm9xrmd03kc0000gn/T/ipykernel_85203/3245240486.py:8: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  q2_4_fare = titanic.pivot_table(values='fare', index='class', columns='sex', aggfunc='sum')

In [8]:
grader.check("q2")

q2 results:
    q2 - 1 result:
        ✅ Test case passed

    q2 - 2 result:
        ✅ Test case passed

    q2 - 3 result:
        ✅ Test case passed

    q2 - 4 result:
        ✅ Test case passed

    q2 - 5 result:
        ✅ Test case passed

    q2 - 6 result:
        ✅ Test case passed

    q2 - 7 result:
        ✅ Test case passed

    q2 - 8 result:
        ❌ Test case failed
        Trying:
            q2_4
        Expecting:
                          age                  fare
            sex        female       male     female       male
            class
            First   34.611765  41.281386  9975.8250  8201.5875
            Second  28.722973  30.740707  1669.7292  2132.1125
            Third   21.750000  26.507589  2321.1086  4393.5865
        **********************************************************************
        Line 1, in q2 7
        Failed example:
            q2_4
        Expected:
                          age                  fare
            sex        female       male     female       male
            class
            First   34.611765  41.281386  9975.8250  8201.5875
            Second  28.722973  30.740707  1669.7292  2132.1125
            Third   21.750000  26.507589  2321.1086  4393.5865
        Got:
            sex               female         male
                 class
            age  First     34.611765    41.281386
                 Second    28.722973    30.740707
                 Third     21.750000    26.507589
            fare First   9975.825000  8201.587500
                 Second  1669.729200  2132.112500
                 Third   2321.108600  4393.586500

## Part 2: Merging Data

We begin by studying four tips files included with this practice: `tips_Thur.csv`, `tips_Fri.csv`, `tips_Sat.csv`, and `tips_Sun.csv`. Each contains information about tips received by servers at a restaurant on the particular days of the week denoted by the file names (Thur for Thursday, Fri for Friday, Sat for Saturday, and Sun for Sunday). Below, we import and preview one of the datasets.

In [ ]:
# Run but do not modify this code
Thur = pd.read_csv("tips_Thur.csv")
Thur.head()

### Question 3
Answer the following questions using the four tips datasets. You will need to combine (using Pandas `concat`) the datasets to answer some of the questions. Furthermore, some of the questions will require information about the day, which is only contained in the file names (though you are welcome to add additional columns to the datasets if you wish).  

1. What is the mean overall `total_bill` including data from all four days? Put your answer in `q3_1` (float).
2. For each of the four days, what is the mean `tip` for that day? Put your answer in `q3_2`. It should have the type `Series` and the index value is the day ('Thur', 'Fri', etc.) and the corresponding data is the mean tip for that day. You should be able to create this by column indexing the `GroupBy` object.
3. Create a pivot table that shows the mean ratio of `tip` to `total_bill` (e.g., if a `tip` is `4` and the `total_bill` is `20`, then the ratio would be `0.2`) grouped by `sex` and day. Put the resulting DataFrame in `q3_3`, the column should be day and index should be sex. You may want to use Pandas `pivot_table` to answer this question.

In [ ]:
# Put your code to answer the question here
# Feel free to add additional cells, especially 
...

In [ ]:
grader.check("q3")

### Question 4
In this question we will work with movie rating data in three different tables/dataframes. You will need to `merge` information from the different tables to answer the questions below. First we import and preview the tables.

In [ ]:
# Run but do not modify this code
users = pd.read_csv("users.csv")
users.head()

In [ ]:
# Run but do not modify this code
ratings = pd.read_csv("ratings.csv")
ratings.head()

In [ ]:
# Run but do not modify this code
movies = pd.read_csv("movies.csv")
movies.head()

Answer the following. 

1. How many movies have been rated at least 100 times? Put the answer in `q4_1` (numpy.int64 or int).
2. Which five users have given the highest average ratings? List their `user_id`s and their average `rating`s. Put the answer in `q4_2`. It should have the type `Series` and the index value is the user_id and the corresponding data is the average rating for that user.
3. Create a pivot table that displays average `rating`s grouped by `sex` and `occupation`. Put the answer table in `q4_3`, the column should be sex and index should be occupation.
4. Which two movies have the most ratings and how many ratings do they have? It should have the type `Series` and the index value is the `movie_title` and the corresponding data is the total number of ratings for that movie.

In [ ]:
# Put your code to answer the question here
# Feel free to add additional cells
q4_1 = ...
q4_2 = ...
q4_3 = ...
q4_4 = ...

In [ ]:
grader.check("q4")

### Question 5
We will work with the `restaurants_A.csv` and `restaurants_B.csv` datasets for this question. Each contain five columns: `id` (a numeric index serving as a unique id, not correlated across the datasets), `name` (of the restaurant), `address` (the street address), `city`, and `type` (the type of restaurant). First we import and preview the data.

In [ ]:
# Run but do not modify this code
df_a = pd.read_csv("restaurants_A.csv")
df_a

In [ ]:
# Run but do not modify this code
df_b = pd.read_csv("restaurants_B.csv")
df_b

Some, but not all, of the restaurants in the two datasets are actually the same. In this question, we would like to consider the problem of merging the datasets. Unfortunately, the `id`s do not correspond between the datasets, so there is no obvious primary key to merge on. In this question, you will explore a fuzzy matching to link the records between the two datasets. You will be asked to use the `edit_dist` function, but you do not need to implement it. An implementation is provided for you in `edit_distance.py`, and you can simply import the function below. It takes two strings as input and returns the edit distance between them.

In [ ]:
# Run but do not modify this code
from edit_distance import edit_dist

# Example of using the edit_dist function
print(edit_dist("hello", "hallo!"))

Answer the following.

1. First, try to perform an inner merge (the default for Pandas `merge`) on the two datasets on the `name` column. How many rows are in the resulting merged dataset? Put your answer in `q5_1`. Why is this value much smaller than the sizes of `df_a` and `df_b`? Put your answer in the "Answer q5" cell.
2. Next, try to perform an inner merge on the two datasets on the `city` column. How many rows are in the resulting merged dataset? Put your answer in `q5_2`. Why is this value much larger than the sizes of `df_a` and `df_b`? Put your answer in the "Answer q5" cell.
3. Find the names of all pairs of records (one from `df_a` and the other from `df_b`) such that the two names have edit distance of 1 or 2 (note that if two strings have edit distance 0, they are exactly the same; you do not need to log these). It is fine to use `for` loops to solve this and your code may take a second or two to run. Put your answer in `q5_3`, it should be a set of tuples (name_a, name_b).
4. Among the names you identified in step 3, which pairs do you think are actually mispellings, and which do you think might actually be different restaurants? Explain your answer using information from other columns beside `name`. Feel free to add additional cells to write code. Put your answer in the "Answer q5" cell.

In [ ]:
# Autograder Note: set is a mutable python keyword used in one of the autochecks, do not initialise any variable named set.
# Put your code to answer the question here
# Feel free to add additional cells
...

In [ ]:
grader.check("q5")

_Type your answer here, replacing this text._

<!-- END QUESTION -->

### Autograder Instructions

Unlike Homeworks, the autograders for worked examples are embedded with the questions so that you can run the tests yourself. To grade your own work, simply run the cell starting with `grader.check` immediately after each question. The cell calls Otter to run the tests for all subquestions and generate a report of what test(s) you pass/do not pass in the same style as on Gradescope.

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()